markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "HJC Blog"
markdown: rdiscount
#markdown: kramdown

author: "HJC"
#disqus: "gopherwood"

navigations:
  - title: 文章
    href: /index.html
  - title: 我
    href: /about.html