markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "HJC Blog"
markdown: rdiscount

author: "HJC"
#disqus: "gopherwood"

navigations:
  - title: 文章
    class: fa fa-list-ul
    href: /index.html
  - title: 标签
    class: fa fa-tags
    href: /tags.html