markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "HJC Blog"
markdown: rdiscount

author: "HJC"
#disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /index.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

