markdown: rdiscount
#pygments: true
permalink: /:year/:month/:day/:title.html
name: "HJC Blog"
markdown: rdiscount
highlighter: pygments
#markdown: kramdown

author: "HJC"
#disqus: "gopherwood"

navigations:
  - title: 文章
    href: /index.html
  - title: 备忘
    href: /mark.html
  - title: 联系我
    href: /about.html
