permalink: /:year/:month/:day/:title.html
name: "HJC Blog"
markdown: kramdown
highlighter: rouge

author: "HJC"

navigations:
  - title: 文章
    href: /index.html
  - title: 备忘
    href: /mark.html
  - title: 联系我
    href: /about.html
